//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public int Age { get; set; }
        public double Salary { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> DesignationID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
